// flow-typed signature: 0580dd0f4ad01ffa2588cb98bbb1bfaa
// flow-typed version: <<STUB>>/oboe_v^2.1.4/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oboe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oboe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oboe/dist/oboe-browser' {
  declare module.exports: any;
}

declare module 'oboe/dist/oboe-browser.min' {
  declare module.exports: any;
}

declare module 'oboe/dist/oboe-node' {
  declare module.exports: any;
}

declare module 'oboe/Gruntfile' {
  declare module.exports: any;
}

declare module 'oboe/test/amd.conf' {
  declare module.exports: any;
}

declare module 'oboe/test/concat.conf' {
  declare module.exports: any;
}

declare module 'oboe/test/http.conf' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/ascentFrom' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/calledLikeMatcher' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/es5-sham' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/es5-shim' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/listMatcher' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/oboeAsserter' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/platform' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/prettyPrintEvents' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/sinon-ie' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/sinon' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/spiedPubSub' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/testUrl' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/testVars' {
  declare module.exports: any;
}

declare module 'oboe/test/libs/toString' {
  declare module.exports: any;
}

declare module 'oboe/test/min.conf' {
  declare module.exports: any;
}

declare module 'oboe/test/require/require' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/amd.integration.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/clarinet.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/defaults.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/detectCrossOrigin.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/errorReport.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/functional.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/incrementalContentBuilder.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/instanceApi.component.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/instanceApi.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/instanceController.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/jsonPath.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/jsonPathTokens.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/lists.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/oboe.component.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/oboe.integration.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/oboe.performance.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/parseResponseHeaders.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/patternAdaptor.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/publicApi.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/pubsub.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/singleEventPubSub.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/streamingHttp.integration.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/streamingHttp.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/specs/streamingXhr.unit.spec' {
  declare module.exports: any;
}

declare module 'oboe/test/streamsource' {
  declare module.exports: any;
}

declare module 'oboe/test/unit.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oboe/dist/oboe-browser.js' {
  declare module.exports: $Exports<'oboe/dist/oboe-browser'>;
}
declare module 'oboe/dist/oboe-browser.min.js' {
  declare module.exports: $Exports<'oboe/dist/oboe-browser.min'>;
}
declare module 'oboe/dist/oboe-node.js' {
  declare module.exports: $Exports<'oboe/dist/oboe-node'>;
}
declare module 'oboe/Gruntfile.js' {
  declare module.exports: $Exports<'oboe/Gruntfile'>;
}
declare module 'oboe/index' {
  declare module.exports: $Exports<'oboe'>;
}
declare module 'oboe/index.js' {
  declare module.exports: $Exports<'oboe'>;
}
declare module 'oboe/test/amd.conf.js' {
  declare module.exports: $Exports<'oboe/test/amd.conf'>;
}
declare module 'oboe/test/concat.conf.js' {
  declare module.exports: $Exports<'oboe/test/concat.conf'>;
}
declare module 'oboe/test/http.conf.js' {
  declare module.exports: $Exports<'oboe/test/http.conf'>;
}
declare module 'oboe/test/libs/ascentFrom.js' {
  declare module.exports: $Exports<'oboe/test/libs/ascentFrom'>;
}
declare module 'oboe/test/libs/calledLikeMatcher.js' {
  declare module.exports: $Exports<'oboe/test/libs/calledLikeMatcher'>;
}
declare module 'oboe/test/libs/es5-sham.js' {
  declare module.exports: $Exports<'oboe/test/libs/es5-sham'>;
}
declare module 'oboe/test/libs/es5-shim.js' {
  declare module.exports: $Exports<'oboe/test/libs/es5-shim'>;
}
declare module 'oboe/test/libs/listMatcher.js' {
  declare module.exports: $Exports<'oboe/test/libs/listMatcher'>;
}
declare module 'oboe/test/libs/oboeAsserter.js' {
  declare module.exports: $Exports<'oboe/test/libs/oboeAsserter'>;
}
declare module 'oboe/test/libs/platform.js' {
  declare module.exports: $Exports<'oboe/test/libs/platform'>;
}
declare module 'oboe/test/libs/prettyPrintEvents.js' {
  declare module.exports: $Exports<'oboe/test/libs/prettyPrintEvents'>;
}
declare module 'oboe/test/libs/sinon-ie.js' {
  declare module.exports: $Exports<'oboe/test/libs/sinon-ie'>;
}
declare module 'oboe/test/libs/sinon.js' {
  declare module.exports: $Exports<'oboe/test/libs/sinon'>;
}
declare module 'oboe/test/libs/spiedPubSub.js' {
  declare module.exports: $Exports<'oboe/test/libs/spiedPubSub'>;
}
declare module 'oboe/test/libs/testUrl.js' {
  declare module.exports: $Exports<'oboe/test/libs/testUrl'>;
}
declare module 'oboe/test/libs/testVars.js' {
  declare module.exports: $Exports<'oboe/test/libs/testVars'>;
}
declare module 'oboe/test/libs/toString.js' {
  declare module.exports: $Exports<'oboe/test/libs/toString'>;
}
declare module 'oboe/test/min.conf.js' {
  declare module.exports: $Exports<'oboe/test/min.conf'>;
}
declare module 'oboe/test/require/require.js' {
  declare module.exports: $Exports<'oboe/test/require/require'>;
}
declare module 'oboe/test/specs/amd.integration.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/amd.integration.spec'>;
}
declare module 'oboe/test/specs/clarinet.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/clarinet.unit.spec'>;
}
declare module 'oboe/test/specs/defaults.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/defaults.unit.spec'>;
}
declare module 'oboe/test/specs/detectCrossOrigin.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/detectCrossOrigin.unit.spec'>;
}
declare module 'oboe/test/specs/errorReport.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/errorReport.unit.spec'>;
}
declare module 'oboe/test/specs/functional.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/functional.unit.spec'>;
}
declare module 'oboe/test/specs/incrementalContentBuilder.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/incrementalContentBuilder.unit.spec'>;
}
declare module 'oboe/test/specs/instanceApi.component.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/instanceApi.component.spec'>;
}
declare module 'oboe/test/specs/instanceApi.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/instanceApi.unit.spec'>;
}
declare module 'oboe/test/specs/instanceController.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/instanceController.unit.spec'>;
}
declare module 'oboe/test/specs/jsonPath.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/jsonPath.unit.spec'>;
}
declare module 'oboe/test/specs/jsonPathTokens.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/jsonPathTokens.unit.spec'>;
}
declare module 'oboe/test/specs/lists.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/lists.unit.spec'>;
}
declare module 'oboe/test/specs/oboe.component.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/oboe.component.spec'>;
}
declare module 'oboe/test/specs/oboe.integration.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/oboe.integration.spec'>;
}
declare module 'oboe/test/specs/oboe.performance.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/oboe.performance.spec'>;
}
declare module 'oboe/test/specs/parseResponseHeaders.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/parseResponseHeaders.unit.spec'>;
}
declare module 'oboe/test/specs/patternAdaptor.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/patternAdaptor.unit.spec'>;
}
declare module 'oboe/test/specs/publicApi.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/publicApi.unit.spec'>;
}
declare module 'oboe/test/specs/pubsub.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/pubsub.unit.spec'>;
}
declare module 'oboe/test/specs/singleEventPubSub.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/singleEventPubSub.unit.spec'>;
}
declare module 'oboe/test/specs/streamingHttp.integration.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/streamingHttp.integration.spec'>;
}
declare module 'oboe/test/specs/streamingHttp.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/streamingHttp.unit.spec'>;
}
declare module 'oboe/test/specs/streamingXhr.unit.spec.js' {
  declare module.exports: $Exports<'oboe/test/specs/streamingXhr.unit.spec'>;
}
declare module 'oboe/test/streamsource.js' {
  declare module.exports: $Exports<'oboe/test/streamsource'>;
}
declare module 'oboe/test/unit.conf.js' {
  declare module.exports: $Exports<'oboe/test/unit.conf'>;
}
